NAME = Colleen
SOURCE = Colleen.c

all : $(NAME)

$(NAME) :
	cc -Wall -Werror -Wextra $(SOURCE) -o $(NAME);

clean :

fclean :
	rm -rf $(NAME)

re :
	make fclean
	make all

.PHONY : all clean fclean re