# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: seojin <seojin@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/10 15:31:17 by seojin            #+#    #+#              #
#    Updated: 2022/11/11 18:01:32 by seojin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ex03
SRCS = main.cpp AMateria.cpp MateriaSource.cpp Character.cpp

include ../template.mk
